name: 'Github Tag Bump Elixir'
description: 'Manage your Elixir app versioning when Bump version by updating mix.exs and pushing git tag for your Elixir projects.'
author: 'Jason Clark'
runs:
  using: 'docker'
  image: 'Dockerfile'
outputs:
  new_tag:
    description: 'Generated tag'
  tag:
    description: 'The latest tag after running this action'
  part:
    description: 'The part of version which was bumped'
branding:
  icon: 'git-merge'  
  color: 'purple'
