name: 'Github Tag Bump Elixir'
description: 'Manage your elixir apps versioning by updating mix.exs and tag master, on merge, with the latest SemVer formatted version.
'
author: 'Jason Clark'
runs:
  using: 'docker'
  image: 'Dockerfile'
outputs:
  new_tag:
    description: 'Generated tag'
  tag:
    description: 'The latest tag after running this action'
  part:
    description: 'The part of version which was bumped'
branding:
  icon: 'git-merge'  
  color: 'purple'
