name: 'Github Tag Bump Elixir'
description: 'Bump update mix.exs and push git tag on merge'
author: 'Jason Clark'
runs:
  using: 'docker'
  image: 'Dockerfile'
outputs:
  new_tag:
    description: 'Generated tag'
  tag:
    description: 'The latest tag after running this action'
  part:
    description: 'The part of version which was bumped'
branding:
  icon: 'git-merge'  
  color: 'purple'
